version: '3.5'
services:
    sgm-web:
        build:
            context: ./..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ./..:/sgm-web:cached
        # Overrides default command so things don't shut down after the process ends.
        command: sleep infinity
        networks:
            - sgm-web-gateway
            - sgm-web-redis
            - sgm-api-gateway
        ports:
            - 3003:3003

    redis:
        image: redis:6
        container_name: sgm-web-redis
        ports:
            - 6333:6379
        networks:
            - sgm-web-redis

networks:
    sgm-web-gateway:
        driver: bridge
        name: sgm-web-gateway
    sgm-web-redis:
        driver: bridge
        name: sgm-web-redis
    sgm-api-gateway:
        external:
            name: sgm-api-gateway

secrets:
    git_ssh_key:
        file: ~/.ssh/git_rsa
